/**
 * Core types for the AI Spend Audit Engine.
 * Following a strict domain-driven design to ensure financial accuracy.
 */

export type ToolId = 
  | "cursor" 
  | "github_copilot" 
  | "claude" 
  | "chatgpt" 
  | "anthropic_api" 
  | "openai_api" 
  | "gemini" 
  | "windsurf";

export type UseCase = "coding" | "writing" | "research" | "data_analysis" | "mixed";
export type PricingModel = "flat" | "per_user" | "usage_based";
export type Priority = "high" | "medium" | "low";
export type Confidence = "certain" | "likely" | "speculative";
export type CompanyStage = "solo" | "startup" | "growth" | "enterprise";

/**
 * Input from the user for a single tool
 */
export interface ToolInput {
  toolId: ToolId;
  toolName: string;
  planId: string;
  monthlySpend: number;
  seats: number;
}

/**
 * Input for the entire audit
 */
export interface AuditInput {
  companyName: string;
  teamSize: number;
  primaryUseCase: UseCase;
  tools: ToolInput[];
}

/**
 * A single pricing tier for a tool
 */
export interface PricingPlan {
  id: string;
  label: string;
  priceMonthly: number | null;
  pricingModel: PricingModel;
  description?: string;
}

/**
 * The catalog structure for a tool
 */
export interface ToolPricing {
  id: ToolId;
  name: string;
  plans: Record<string, PricingPlan>;
}

/**
 * A recommendation generated by the rules engine
 */
export interface Recommendation {
  id: string;
  toolId: ToolId;
  toolName: string;
  action: "downgrade" | "consolidate" | "cancel" | "optimize" | "switch" | "advisory";
  currentPlanId: string;
  recommendedPlanId: string;
  currentMonthlyCost: number;
  optimizedMonthlyCost: number;
  monthlySavings: number;
  reason: string;
  priority: Priority;
  confidence: Confidence;
  layer: number;
}

/**
 * The final output of the audit engine
 */
export interface AuditResult {
  companyName: string;
  companyStage: CompanyStage;
  currentMonthlySpend: number;
  optimizedMonthlySpend: number;
  monthlySavings: number;
  annualSavings: number;
  verdict: string;
  recommendations: Recommendation[];
  summaryMetadata: {
    totalToolsAnalyzed: number;
    potentialSavingsPercentage: number;
    topSavingOpportunity: string | null;
    isOptimized: boolean;
  };
}

/**
 * Interface for a business rule
 */
export interface AuditRule {
  id: string;
  check: (input: AuditInput, tool: ToolInput) => Recommendation | null;
}
