/**
 * Core types for the Audit Engine.
 * Following a strict domain-driven design to ensure financial accuracy.
 */

export type ToolId = 
  | "cursor" 
  | "github_copilot" 
  | "claude" 
  | "chatgpt" 
  | "anthropic_api" 
  | "openai_api" 
  | "gemini" 
  | "windsurf";

export type UseCase = "coding" | "marketing" | "customer_support" | "operations" | "general";

export type PricingModel = "flat" | "per_user" | "usage_based";

/**
 * Input from the user for a single tool
 */
export interface ToolInput {
  toolId: ToolId;
  planId: string;
  monthlySpend: number;
  seats: number;
}

/**
 * Input for the entire audit
 */
export interface AuditInput {
  companyName: string;
  teamSize: number;
  useCase: UseCase;
  tools: ToolInput[];
}

/**
 * A single pricing tier for a tool
 */
export interface PricingPlan {
  id: string;
  label: string;
  priceMonthly: number | null; // null for custom/enterprise
  pricingModel: PricingModel;
  description?: string; // Optional to prevent strict catalog errors during updates
}

/**
 * The catalog structure for a tool
 */
export interface ToolPricing {
  id: ToolId;
  name: string;
  plans: Record<string, PricingPlan>;
}

/**
 * A recommendation generated by the rules engine
 */
export interface Recommendation {
  toolId: ToolId;
  toolName: string;
  currentPlanId: string;
  recommendedPlanId: string;
  currentMonthlyCost: number;
  optimizedMonthlyCost: number;
  monthlySavings: number;
  reason: string;
  priority: "high" | "medium" | "low";
  action: "downgrade" | "consolidate" | "switch" | "optimize";
}

/**
 * Interface for a business rule
 */
export interface AuditRule {
  id: string;
  check: (input: AuditInput, tool: ToolInput) => Recommendation | null;
}

/**
 * The final output of the audit
 */
export interface AuditResult {
  companyName: string;
  currentMonthlySpend: number;
  optimizedMonthlySpend: number;
  monthlySavings: number;
  annualSavings: number;
  recommendations: Recommendation[];
  summaryMetadata: {
    totalToolsAnalyzed: number;
    potentialSavingsPercentage: number;
    topSavingOpportunity: string | null;
  };
}
